### ISSUE TITLE
Automate `manage.py migrate` after `git pull`

### ISSUE THREAD

**Issue by asvdf** [cryptosharks131/lndg#15]
LNDg now runs on a tight update schedule, which is very good.
I know a migration is usually needed after an update to make the database get on par with the release, I just always forget how to do that, so I need to open this repository and scroll down until I find the reference to the `.venv/bin/python manage.py migrate` command.

Suggestion: either make it so (probably would be hackish) that in git pull, there is some sort of notification that verbosely remembers to run that specific command, or better yet have `jobs.py` check if the release has been updated, and instead of running the DB update jobs for that cycle, call the migration command instead.

**Comment by cryptosharks131** [comment]
This may be possible but it would require some work around making LNDg aware of version changes and adding a check to jobs.py on this condition.

It would also only be useful for manual install users as the Docker installs do not share this concern since each container gets migrated after spin up.

Would it be an improvement to run `initialize.py` again after updating instead of remembering the `manage.py migrate`? As of v1.0.0 the `initialize.py` file will also migrate any database changes and can replace the `manage.py migrate` step.

**Comment by asvdf** [comment]
Probably still better, so just manually issue `./initialize.py` instead of the migrate command?
I thought checking version changes could be implemented, albeit somewhat of a "dirty hack", by having `jobs.py` create a `version.txt` if it doesn't exists, and containing version number, and running migration when instead file exists and string inside is `<` current version string.

**Comment by cryptosharks131** [comment]
Yeah exactly, running `./initialize.py` will migrate any database changes now.

Then you could technically make `./initialize.py` part of your startup for LNDg so you wont have to remember any longer.

**Comment by asvdf** [comment]
Sounds fair enough

**Comment by cryptosharks131** [comment]
Added migrate in intialize.py as part of #14
