### ISSUE TITLE
Drop iTarget or oTarget for rebalancing channels

### ISSUE THREAD

**Issue by proof-of-reality** [cryptosharks131/lndg#159]
Behaviour is achievable by only using one of the threshold as follows
--

1. **if only oTarget is configurable:**
> - if oTarget is below the current outbound liquidity: allow AR to be enabled/disabled
> - if oTarget is above the current outbound liquidity: channel work as liquidity source

2. **Similarly for iTarget:**
> - if iTarget is above the current inbound liquidity: allow AR to be enabled/disabled
> - if iTarget is below the current inbound liquidity: channel work as liquidity source

---

Same goes for Autopilot (AP) since it will enable/disable AR automatically according to oTarget|iTarget thresholds shown in the first cases above

**Comment by Bitcoinite** [comment]
Thanks for your proposal. Let me explain the situation:

Imagine a channel acts as a source. I only want to push out it and under no circumstances, I want to rebalance into it.
My current settings for such a channel are oTarget 10% and iTarget 100%.

With your proposed changes this would not be possible.

Scenario 1 (only oTarget is configurable):
I would set oTarget to 10%. Everything will go fine until the channel hits 10% Outbound and 90% Inbound. Now AP would be allowed to enable AR and the channel would be rebalanced. Setting Max Cost to 0 wouldn't even help since there are 0 fee routes to rebalance the channel.

Scenario 2 (only iTarget is configurable):
The same issue as described above but for sink channels. Imagine a Channel I never want to use as a source for rebalances. Now my usual settings would be 100% oTarget and 10% iTarget. With your proposal, I wouldn't be able to define the 100% oTarget. Therefore the AP could define the channel as a source and disable AR, which would lead to a situation where the channel would be used to rebalance out of. Setting Max Cost wouldn't matter at all.

Conclusion: Neither of your proposed solutions would work in a real life scenario.
