### ISSUE TITLE
Can't parse "Unknown Next Peer" in the Failed HTLCs

### ISSUE THREAD

**Issue by studioTeaTwo** [cryptosharks131/lndg#173]
## Error description
channelId & peer of outbound is wrong.(Maybe amount, too)
![スクリーンショット 2022-11-17 18 45 32](https://user-images.githubusercontent.com/1317305/202433546-c52f1349-49a3-46be-872d-33edc7ad4271.png)

`lnd.log` confirms that the corresponding log is correct. It's normal Inactive channel.

## Situation
I installed [lnd@0.15.4-beta-build-2](https://github.com/getumbrel/umbrel-apps/commit/5a389ac58fb5662eae44b7e90c638813630f587e) in Umbrel.
After that I seem to get this error.

**Comment by studioTeaTwo** [comment]
UPDATE: Another person's situation is different. He got the error before `lnd@0.15.4-beta-build-2`. But the fact that it happened in the last few days is the same.

**Comment by cryptosharks131** [comment]
The error `Unknown Next Peer` is generated directly from LND and passed through to you in LNDg. This htlc failure code does get returned to the sender of a payment if the channel is offline.
https://github.com/lightningnetwork/lnd/blob/e7170ef81970fcbac5dc0330e2cb21f6a9f5ee7a/lnrpc/lightning.proto#L4303

The channel alias and current liquidity amounts are showing as `None` because for some reason LNDg has not seen this channel id before. Maybe you have not loaded your current channels with jobs.py yet, the channel was closed before using LNDg for the first time or the channel id from the htlc is just invalid.

**Comment by studioTeaTwo** [comment]
All right. `Unknown Next Peer`'s log has been normal now. While some channels confirmed in lnd.log, when was strange was only for these few days. Thanks for investigating!
