### ISSUE TITLE
Auto-Fees

### ISSUE THREAD

**Issue by InsaneSplash** [cryptosharks131/lndg#198]
Since moving to Version 1.4 and 1.5 I am unable to get my service to auto-adjust the fee rates.
I do have AF-Enabled and have tried a few changes, but the only thing I can do right now manual adjustments.

Is there a way to investigate why this is failing?

**Comment by cryptosharks131** [comment]
The AF should run whenever your data gets refreshed. Are you seeing the most recent activity on your dashboard?

Also, be sure the AF option is enabled on individual channels as well. You can update this from the channel card or the Fee Rates page.

**Comment by cryptosharks131** [comment]
It looks like either the jobs service isn't running or you are still loading older historical data. The AF needs current data in order to set fees (last 7 days). If you are loading a lot of historical data, check this other issue to see if removing some of your old payment data helps speed things up.

Slow loading data issue: https://github.com/cryptosharks131/lndg/issues/197

**Comment by InsaneSplash** [comment]
I ran ```lncli deletepayments --all``` and it seems to have helped solve the problem... AF is now working.
I wonder if there is a way to stop this from happening again.... Do I run this weekly?

**Comment by cryptosharks131** [comment]
This should not be required again as the historical data is stored indefinitely in the sqlite3 database.
