### ISSUE TITLE
IndexError at Step 8 of install process: Generate some initial data for your dashboard

### ISSUE THREAD

**Issue by TrezorHannes** [cryptosharks131/lndg#2]
Steps 1-7 work fine. When calling command for Step 8, the following results follow
```
$ admin@raspberrypi:~/lndg $ .venv/bin/python jobs.py
Traceback (most recent call last):
  File "jobs.py", line 220, in <module>
    main()
  File "jobs.py", line 215, in main
    update_invoices(stub)
  File "jobs.py", line 91, in update_invoices
    alias = Channels.objects.filter(chan_id=invoice.htlcs[0].chan_id)[0].alias
  File "/home/admin/lndg/.venv/lib/python3.7/site-packages/django/db/models/query.py", line 318, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
```

**Comment by cryptosharks131** [comment]
This appears to happen because of a channel lndg does not know about (likely opened and closed already) and was used to fulfill the invoice it's trying to import. Not a problem for new nodes but is for existing nodes with closed channels.

Should have a solution for this soon.

**Comment by cryptosharks131** [comment]
Thanks again for your report, I have addressed this issue in the most recent commit. Please follow the instructions on the README page to update.

I have also included a change that will require another setting variable in the `lndg/settings.py` fle in order to help facilitate using lndg on other networks. You can add it to the file directly using `LND_NETWORK = 'mainnet'` or alternatively you can generate a new settings.py file by running the `.venv/bin/python initialize.py` command again.
