### ISSUE TITLE
Badgateway 502 - Nginx - issue on RaspiBlitz

### ISSUE THREAD

**Issue by Steve-too** [cryptosharks131/lndg#345]
I'm not too technical but I know my way around and have followed all instructions but I'm not able to connect to LNDg via my webbrowser. When I type in the ip-addres and port number in the webbrowser I get a Bad Gateway 502 error.

example:  http://192.168.2.178:8889

As said I'm not too technical and need help to troubleshoot this issue to resolve it. Thank you for you help (and patience ;-))

**Comment by cryptosharks131** [comment]
This seems to be operational. Maybe check for clues in the nginx logs as well. They should be here:
`/var/log/nginx/`

**Comment by Steve-too** [comment]
Thanks again - in the error.log I find the following when accessing 192.168.2.178:8889 via Safari webbrowser

2023/11/28 16:46:10 [crit] 1723225#1723225: *228 connect() to unix:///home/admin/lndg/lndg.sock failed (13: Permission denied) while connecting to upstream, client: 192.168.2.148, server: _, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/admin/lndg/lndg.sock:", host: "192.168.2.178:8889"
2023/11/28 16:46:14 [crit] 1723225#1723225: *227 connect() to unix:///home/admin/lndg/lndg.sock failed (13: Permission denied) while connecting to upstream, client: 192.168.2.148, server: _, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/admin/lndg/lndg.sock:", host: "192.168.2.178:8889"

**Comment by cryptosharks131** [comment]
It seems like there is a permission issue with the `lndg.sock` file. You can try to resolve this so that both uwsgi and nginx are able to read/write to this file.

One thing that helped some resolve this issue was to update `/etc/nginx/sites-enabled/lndg` with `user admin` at the top of the file. You will need to restart nginx afterwards. `sudo systemctl restart nginx`
